### Practicing/Testing Python Kernel Tensorflow Basics and Installation

In [1]:
import numpy as np
import tensorflow as tf


2025-04-26 12:25:43.258186: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
print('TensorFlow version:', tf.version)
print('NumPy version:', np.__version__)

TensorFlow version: <module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/site-packages/tensorflow/_api/v2/version/__init__.py'>
NumPy version: 1.24.3


## Tensors 
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.


In [3]:
string = tf.Variable('Hello, TensorFlow!')
number = tf.Variable(324, dtype=tf.int16)
floating = tf.Variable(3.567, dtype=tf.float64)

## Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a _tensor of rank 0_, also known as a __scalar__.

- Below notice how the _rank_ of the tensor is practically __the deepest level of nested lists/arrays.__

In [4]:
rank1_tensor = tf.Variable(["Test"], dtype=tf.string)
rank2_tensor = tf.Variable([[1, 2, 3,], [4, 5, 6]], dtype=tf.int32)

tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensors

- The shape of a tensor is simply __the number of elements that exist in each dimension.__ TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.
- The shape can be output using the `.shape` attribute on a tensor

In [ ]:
# Notice how there are 2 inner lists in rank2_tensor, each with 3 elements
rank2_tensor.shape

TensorShape([2, 3])

## Changing Shape
- The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

In [9]:
tensor1 = tf.ones([1,2,3])  # Expect to look like [[[1,1,1],[1,1,1]]]
print(tensor1)
# We have 6 elements in this tensor1. So we can reshape the tensor to anything that combines to 6 elements. 
tensor2 = tf.reshape(tensor1, [2, 3, 1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 directs the tensor to calculate the size of the dimension in that place for us. (in this case it will calculate 2 elements: [3, 2])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
